services:
  visionbot:
    build:
      context: .
      dockerfile: src/vision_bot/Dockerfile
    image: visionbot:jazzy
    container_name: visionbot_dev
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - ./src:/home/ubuntu/ros2_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home/ubuntu/ros2_ws
